version: '3.8'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: sql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1YourStrong!Password
    ports:
      - 1433:1433
